let products = [{
    id: '1',
    name: 'Austin wood',
    brand: "Roadster",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522838/t-shirt/products/n1_gzhokr.jpg',
    desc: "This season set a sporty fashion trend with the HRX Men's Athleisure T-shirt. This striped casual T-shirt can be worn on its own or layered under a jacket or a hoodie.",
    price: '535',
},
{
    id: '2',
    name: 'Mast & Harbour',
    brand: "Kalt",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522837/t-shirt/products/n2_rhb62n.jpg',
    desc: "Keep this hip this season with the HRX Men's Athleisure T-shirt. This versatile T-shirt can be styled any way you like for the ultimate gym-to-street look.",
    price: '445',
},
{
    id: '3',
    name: 'Tommy Hilfiger',
    brand: "Kalt",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522837/t-shirt/products/n3_clm5zr.jpg',
    desc: 'White solid formal shirt, has a spread collar, long sleeves, button placket, and straight hem',
    price: '745',
},
{
    id: '4',
    name: 'Roadster HRX',
    brand: "Roadster",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522837/t-shirt/products/n4_ciwvk8.jpg',
    desc: 'Red and Grey melange colourblocked sweatshirt has a hood, 2 insert pockets, long sleeves, and ribbed hem',
    price: '845',
},
{
    id: '5',
    name: 'Dillinger',
    brand: "Puma",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522838/t-shirt/products/n5_kt5pnu.jpg',
    desc: 'Red and Grey melange colourblocked sweatshirt has a hood, 2 insert pockets, long sleeves, and ribbed hem',
    price: '1545',
},
{
    id: '6',
    name: 'Nautica',
    brand: "Puma",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522838/t-shirt/products/n6_e8kr1s.jpg',
    desc: 'Black and white checked casual shirt, has a mandarin collar, long sleeves, curved hem',
    price: '789',
},
{
    id: '7',
    name: 'vanHeusen',
    brand: "Kalt",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522838/t-shirt/products/n7_b3ln1c.jpg',
    desc: 'Black and white checked casual shirt, has a mandarin collar, long sleeves, curved hem',
    price: '475',
}, {
    id: '8',
    name: 'U.S.Polo',
    brand: "Roadster",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522838/t-shirt/products/n8_mtrwdd.jpg',
    desc: 'Black and white checked casual shirt, has a mandarin collar, long sleeves, curved hem',
    price: '1545',
}
]


let newProducts = [{
    id: '9',
    name: 'Vanadium',
    brand: "Kalt",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522837/t-shirt/products/f1_yhzyha.jpg',
    desc: 'Relaxed-fit top in sweatshirt fabric made from a cotton blend with dropped shoulders and ribbing around the neckline, cuffs and hem. Soft brushed inside.',
    price: '757',
},
{
    id: '10',
    name: 'Allensolly',
    brand: "Allen Solley",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522836/t-shirt/products/f2_gtuuw6.jpg',
    desc: 'Relaxed-fit top in sweatshirt fabric made from a cotton blend with dropped shoulders and ribbing around the neckline, cuffs and hem. Soft brushed inside.',
    price: '1300',
},

{
    id: '11',
    name: 'MAX',
    brand: "Roadster",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522833/t-shirt/products/f4_pnpcel.jpg',
    desc: 'Relaxed-fit top in sweatshirt fabric made from a cotton blend with dropped shoulders and ribbing around the neckline, cuffs and hem. Soft brushed inside.',
    price: '445',
},
{
    id: '12',
    name: 'Dennis lingo',
    brand: "Puma",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522836/t-shirt/products/f5_a6vc0j.jpg',
    desc: "Keep this hip this season with the HRX Men's Athleisure T-shirt. This versatile T-shirt can be styled any way you like for the ultimate gym-to-street look.",
    price: '1400',
},
{
    id: '13',
    name: 'H&Men',
    brand: "Allen Solley",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522835/t-shirt/products/f6_nnjo4f.jpg',
    desc: "Keep this hip this season with the HRX Men's Athleisure T-shirt. This versatile T-shirt can be styled any way you like for the ultimate gym-to-street look.",
    price: '1200',
},
{
    id: '14',
    name: 'Allen',
    brand: "Allen Solley",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522834/t-shirt/products/f7_mn4mgu.jpg',
    desc: "Keep this hip this season with the HRX Men's Athleisure T-shirt. This versatile T-shirt can be styled any way you like for the ultimate gym-to-street look.",
    price: '987',
},
{
    id: '15',
    name: 'Spykar',
    brand: "Puma",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522837/t-shirt/products/f8_rzwttg.jpg',
    desc: "Keep this hip this season with the HRX Men's Athleisure T-shirt. This versatile T-shirt can be styled any way you like for the ultimate gym-to-street look.",
    price: '890',
},
{
    id: '16',
    name: 'Friskers',
    brand: "Kalt",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522836/t-shirt/products/f3_o9tore.jpg',
    desc: 'Relaxed-fit top in sweatshirt fabric made from a cotton blend with dropped shoulders and ribbing around the neckline, cuffs and hem. Soft brushed inside.',
    price: '670',
}]


// allProducts

productData = [{
    id: '1',
    name: 'Austin wood',
    brand: "Roadster",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522838/t-shirt/products/n1_gzhokr.jpg',
    desc: "This season set a sporty fashion trend with the HRX Men's Athleisure T-shirt. This striped casual T-shirt can be worn on its own or layered under a jacket or a hoodie.",

    price: '535',
},
{
    id: '2',
    name: 'Mast & Harbour',
    brand: "Kalt",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522837/t-shirt/products/n2_rhb62n.jpg',
    desc: "Keep this hip this season with the HRX Men's Athleisure T-shirt. This versatile T-shirt can be styled any way you like for the ultimate gym-to-street look.",
    price: '445',
},
{
    id: '3',
    name: 'Tommy Hilfiger',
    brand: "Kalt",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522837/t-shirt/products/n3_clm5zr.jpg',
    desc: 'White solid formal shirt, has a spread collar, long sleeves, button placket, and straight hem',
    price: '745',
},
{
    id: '4',
    name: 'Roadster HRX',
    brand: "Roadster",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522837/t-shirt/products/n4_ciwvk8.jpg',
    desc: 'Red and Grey melange colourblocked sweatshirt has a hood, 2 insert pockets, long sleeves, and ribbed hem',
    price: '845',
},
{
    id: '5',
    name: 'Dillinger',
    brand: "Puma",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522838/t-shirt/products/n5_kt5pnu.jpg',
    desc: 'Red and Grey melange colourblocked sweatshirt has a hood, 2 insert pockets, long sleeves, and ribbed hem',
    price: '1545',
},
{
    id: '6',
    name: 'Nautica',
    brand: "Puma",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522838/t-shirt/products/n6_e8kr1s.jpg',
    desc: 'Black and white checked casual shirt, has a mandarin collar, long sleeves, curved hem',
    price: '789',
},
{
    id: '7',
    name: 'vanHeusen',
    brand: "Kalt",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522838/t-shirt/products/n7_b3ln1c.jpg',
    desc: 'Black and white checked casual shirt, has a mandarin collar, long sleeves, curved hem',
    price: '475',
}, {
    id: '8',
    name: 'U.S.Polo',
    brand: "Roadster",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522838/t-shirt/products/n8_mtrwdd.jpg',
    desc: 'Black and white checked casual shirt, has a mandarin collar, long sleeves, curved hem',
    price: '1545',
},


{


    id: '9',
    name: 'Vanadium',
    brand: "Kalt",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522837/t-shirt/products/f1_yhzyha.jpg',
    desc: 'Relaxed-fit top in sweatshirt fabric made from a cotton blend with dropped shoulders and ribbing around the neckline, cuffs and hem. Soft brushed inside.',
    price: '757',
},
{
    id: '10',
    name: 'Allen',
    brand: "Allen Solley",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522836/t-shirt/products/f2_gtuuw6.jpg',
    desc: 'Relaxed-fit top in sweatshirt fabric made from a cotton blend with dropped shoulders and ribbing around the neckline, cuffs and hem. Soft brushed inside.',
    price: '1300',
},

{
    id: '11',
    name: 'MAX',
    brand: "Roadster",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522833/t-shirt/products/f4_pnpcel.jpg',
    desc: 'Relaxed-fit top in sweatshirt fabric made from a cotton blend with dropped shoulders and ribbing around the neckline, cuffs and hem. Soft brushed inside.',
    price: '445',
},
{
    id: '12',
    name: 'Dennis lingo',
    brand: "Puma",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522836/t-shirt/products/f5_a6vc0j.jpg',
    desc: "Keep this hip this season with the HRX Men's Athleisure T-shirt. This versatile T-shirt can be styled any way you like for the ultimate gym-to-street look.",
    price: '1400',
},
{
    id: '13',
    name: 'H&Men',
    brand: "Allen Solley",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522835/t-shirt/products/f6_nnjo4f.jpg',
    desc: "Keep this hip this season with the HRX Men's Athleisure T-shirt. This versatile T-shirt can be styled any way you like for the ultimate gym-to-street look.",
    price: '1200',
},
{
    id: '14',
    name: 'Allen',
    brand: "Allen Solley",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522834/t-shirt/products/f7_mn4mgu.jpg',
    desc: "Keep this hip this season with the HRX Men's Athleisure T-shirt. This versatile T-shirt can be styled any way you like for the ultimate gym-to-street look.",
    price: '987',
},
{
    id: '15',
    name: 'Spykar',
    brand: "Puma",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522837/t-shirt/products/f8_rzwttg.jpg',
    desc: "Keep this hip this season with the HRX Men's Athleisure T-shirt. This versatile T-shirt can be styled any way you like for the ultimate gym-to-street look.",
    price: '890',
},
{
    id: '16',
    name: 'Friskers',
    brand: "Kalt",
    img: 'https://res.cloudinary.com/denokpulg/image/upload/v1656522836/t-shirt/products/f3_o9tore.jpg',
    desc: 'Relaxed-fit top in sweatshirt fabric made from a cotton blend with dropped shoulders and ribbing around the neckline, cuffs and hem. Soft brushed inside.',
    price: '670',
}];